// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stfcqbxuscflzkvbculf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0ZmNxYnh1c2NmbHprdmJjdWxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MjM4ODcsImV4cCI6MjA2ODM5OTg4N30.Ng6Cou5SyHxWf6EnoZOl-ItiJb_fy__8qSH65V7VNbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});